title: Rodney Lafuente Mercado

author:
  name: Rodney Lafuente Mercado
  email: lafuentemercado@college.harvard.edu

plugins:
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/rodlaf" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/lafuente-mercado" }

header_pages:
  - index.md
  - resume.md
  - blog.md

show_excerpts: true