title: Rodney Lafuente Mercado
author:
  name: Rodney Lafuente Mercado
  email: lafuentemercado [at] college [dot] harvard [dot] edu

# description: My personal website.

plugins:
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/rodlaf" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/lafuente-mercado" }

  skin:
    solarized

header_pages:
  - index.md
  - posts.md

show_excerpts: true