title: Rodney's Page
author:
  name: Rodney Lafuente Mercado
  email: lafuentemercado@college.harvard.edu

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  My personal blog/website.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/rodlaf" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/lafuente-mercado" }

  skin:
    dark

header_pages:
  - about.md

show_excerpts: false