title: Rodney's Page
author:
  name: Rodney Lafuente Mercado
  email: lafuentemercado@college.harvard.edu

# description: My personal website.

plugins:
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/rodlaf" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/lafuente-mercado" }

  skin:
    dark

header_pages:
  - about.md
  - index.md

show_excerpts: false